### PR TITLE
use spack stage -p instead

### PR DESCRIPTION
**Pull request by gartung**

### CODE REVIEW

**Comment by gartung** [comment]
@chissg  this seems to do the correct thing. I could not get spackdev init to work correctly. 

spackdev init  cetlib
==> requested packages: cetlib
==> spack_cmd: spec 1.92226004601s
==> warning: ninja build selected, but neither "ninja" nor "ninja-build" are available
==> creating wrapper scripts
==> spack_cmd: env 0.275339126587s
==> spack_cmd: env 0.275339126587s
==> Error: spack command output:
==> Error: unrecognized arguments: --dump
==> Error: spack command "spack env --dump cetlib cetlib-environment.txt" failed with return value 256

With the spackdev directory created the stage command works...

spackdev stage  cetlib
==> staging cetlib
==> staging cetlib
==> spack_cmd: -d 1.93489098549s

**Comment by gartung** [comment]
So now spackdev init works but I can't move a directory named .tmp/cetlib because the cetlib directory exists...

[gartung@woof spackdev]$ find *
cetlib
cetlib/bin
cetlib/bin/gfortran
cetlib/bin/cmake
cetlib/bin/g++
cetlib/bin/gcc
cetlib/env
cetlib/env/env.sh
CMakeLists.txt
packages.sd

**Comment by greenc-FNAL** [comment]
Why the `rsync` rather than `shutil.move`?

**Comment by gartung** [comment]
The init command create a directory named $package in spacdev. Doing shutil.move would leave spacdev/$package/$package

**Comment by gartung** [comment]
I was unclear on what directory the original code did the checkout in.

**Pull request merged**
